# Generated by Django 5.0.2 on 2024-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=150)),
                ('high', models.FloatField(max_length=15)),
                ('low', models.FloatField(max_length=15)),
                ('open', models.FloatField(max_length=15)),
                ('close', models.FloatField(max_length=15)),
                ('volume', models.IntegerField(max_length=15)),
            ],
        ),
    ]
